name: Deploy to GitHub Pages

on:
  push:
    branches:
        - main
    paths:
        - 'index.html'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
     id-token: write
     contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Deployment Directory
        run: |
         mkdir -p _site
         cp index.html _site/

      - name: Archive Artifact
        run: tar -czf site.tar.gz _site/

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
